export const BRIEFINGS = {
  introduction: {
    kind: 'lesson',
    title: 'Introduction',
    jpTitle: 'はじめまして',
    level: 'N5',
    minutes: 8,
    accent: 'moss',
    startHref: '/chat/sensei?briefing=introduction&type=lesson',
    summary: 'Practice your first self-introduction with simple, confident sentences.',
    headsUp: [
      'Keep answers short: name, origin, and one like.',
      'Use はじめまして at the start, then よろしくお願いします at the end.',
      'KAIwa will nudge you if particles feel off.',
    ],
    prep: ['私は ___ です', '___ が好きです', 'よろしくお願いします'],
  },
  'common-phrases': {
    kind: 'lesson',
    title: 'Common Phrases',
    jpTitle: 'よく使う表現',
    level: 'N5',
    minutes: 12,
    accent: 'mustard',
    startHref: '/chat/sensei?briefing=common-phrases&type=lesson',
    summary: 'Warm up everyday phrases for greetings, thanks, apologies, and quick replies.',
    headsUp: [
      'Listen for formality: です and ます keep it polite.',
      'Short natural replies are better than long translated sentences.',
      'Repeat a phrase once if you want KAIwa to drill it.',
    ],
    prep: ['ありがとうございます', 'すみません', '大丈夫です'],
  },
  'likes-dislikes': {
    kind: 'lesson',
    title: 'Likes & Dislikes',
    jpTitle: '好き・嫌い',
    level: 'N5',
    minutes: 10,
    accent: 'correction',
    startHref: '/chat/sensei?briefing=likes-dislikes&type=lesson',
    summary: 'Talk about what you like, dislike, and want to try next.',
    headsUp: [
      'Use が with 好き: コーヒーが好きです.',
      'Add とても or ちょっと to soften your answer.',
      'Expect follow-up questions asking why.',
    ],
    prep: ['___ が好きです', '___ はちょっと苦手です', 'どうしてですか'],
  },
  'basic-verbs': {
    kind: 'lesson',
    title: 'Basic Verbs',
    jpTitle: '基本動詞',
    level: 'N5',
    minutes: 15,
    accent: 'aizome',
    startHref: '/chat/sensei?briefing=basic-verbs&type=lesson',
    summary: 'Use daily action verbs in short present and past-tense sentences.',
    headsUp: [
      'Focus on one verb per sentence.',
      'KAIwa may ask what you did today or what you do every morning.',
      'If stuck, answer with the verb stem and KAIwa will scaffold it.',
    ],
    prep: ['食べます', '行きます', '見ました'],
  },
  'simple-sentences': {
    kind: 'lesson',
    title: 'Simple Sentences',
    jpTitle: '簡単な文',
    level: 'N5',
    minutes: 14,
    accent: 'mustard',
    startHref: '/chat/sensei?briefing=simple-sentences&type=lesson',
    summary: 'Build clean subject-topic sentences without overthinking grammar.',
    headsUp: [
      'Start with topic は, then say one clear thing.',
      'It is okay to answer slowly and revise.',
      'KAIwa will keep corrections small and actionable.',
    ],
    prep: ['今日は ___ です', '私は ___ に行きます', 'これは ___ です'],
  },
  'personal-info': {
    kind: 'lesson',
    title: 'Personal Info',
    jpTitle: '自己紹介',
    level: 'N5',
    minutes: 9,
    accent: 'moss',
    startHref: '/chat/sensei?briefing=personal-info&type=lesson',
    summary: 'Answer common questions about yourself with safe local-first profile memory.',
    headsUp: [
      'Only share details you want saved locally on this device.',
      'Practice name, country, work or school, and hobbies.',
      'KAIwa can remember your preferred name for later sessions.',
    ],
    prep: ['お名前は？', 'どこから来ましたか', '趣味は何ですか'],
  },
  'ordering-food': {
    kind: 'lesson',
    title: 'Ordering Food',
    jpTitle: '注文する',
    level: 'N5',
    minutes: 11,
    accent: 'correction',
    startHref: '/chat/sensei?briefing=ordering-food&type=lesson',
    summary: 'Order politely, ask for recommendations, and confirm what you want.',
    headsUp: [
      'Use ___ をください for simple orders.',
      'Pointing language is useful: これ, それ, あれ.',
      'Expect a confirmation question before checkout.',
    ],
    prep: ['これをください', 'おすすめは何ですか', '水をお願いします'],
  },
  'meme-replies': {
    kind: 'lesson',
    title: 'Meme Replies',
    jpTitle: 'ネット表現',
    level: 'N4',
    minutes: 7,
    accent: 'aizome',
    startHref: '/chat/sensei?briefing=meme-replies&type=lesson',
    summary: 'Practice light internet replies while keeping tone natural and friendly.',
    headsUp: [
      'Casual Japanese can sound too blunt if translated directly.',
      'KAIwa will flag phrases that are funny but risky.',
      'Short reactions are the goal here.',
    ],
    prep: ['かわいい', 'おもしろい', 'ほんとう？'],
  },
  'custom-lesson': {
    kind: 'lesson',
    title: 'Custom Lesson',
    jpTitle: 'カスタム練習',
    level: 'Adaptive',
    minutes: 10,
    accent: 'mustard',
    startHref: '/chat/sensei?briefing=custom-lesson&type=lesson',
    summary: 'Bring any topic and KAIwa will turn it into a short guided practice.',
    headsUp: [
      'Start with a topic, goal, or phrase you want to practice.',
      'KAIwa will keep the session local-first unless you configured an external provider.',
      'You can ask for easier or harder Japanese at any time.',
    ],
    prep: ['今日のテーマは ___', 'もっと簡単に', 'もう一回お願いします'],
  },
  'train-station': {
    kind: 'roleplay',
    title: 'Train Station',
    jpTitle: '駅で迷った時',
    level: 'N5',
    minutes: 8,
    accent: 'mustard',
    startHref: '/chat/sensei?briefing=train-station&type=roleplay',
    image: '/assets/bg_eki_homedoor_train_open.jpg',
    summary: 'You are at a station and need help finding the right platform.',
    headsUp: [
      'Say where you want to go first.',
      'Listen for platform numbers and direction words.',
      'すみません is your safest opener.',
    ],
    prep: ['___ に行きたいです', '何番線ですか', 'ありがとうございます'],
  },
  'idol-cheki': {
    kind: 'roleplay',
    title: 'Idol Cheki',
    jpTitle: 'ライブ後の一言',
    level: 'N4',
    minutes: 6,
    accent: 'correction',
    startHref: '/chat/idol?briefing=idol-cheki&type=roleplay',
    image: '/assets/bg_music_live_stage.jpg',
    summary: 'You get a quick post-live cheki moment and want to say something warm.',
    headsUp: [
      'Keep it short; the scene is fast.',
      'Compliments should be simple and sincere.',
      'KAIwa will help you avoid overly direct translations.',
    ],
    prep: ['ライブ最高でした', '応援しています', 'また来ます'],
  },
  'colleague-hiroen': {
    kind: 'roleplay',
    title: 'Colleague Hiroen',
    jpTitle: '同僚と雑談',
    level: 'N3',
    minutes: 12,
    accent: 'aizome',
    startHref: '/chat/sensei?briefing=colleague-hiroen&type=roleplay',
    image: '/assets/bg_ryokan_hiroen.jpg',
    summary: 'Practice a relaxed work-adjacent chat with a colleague after hours.',
    headsUp: [
      'Use polite casual balance: friendly, not too stiff.',
      'Ask one follow-up before changing topics.',
      'KAIwa will model softer phrasing when needed.',
    ],
    prep: ['お疲れさまです', '週末は何をしましたか', 'いいですね'],
  },
  'convenience-store': {
    kind: 'roleplay',
    title: 'Convenience Store',
    jpTitle: 'コンビニ会話',
    level: 'N5',
    minutes: 7,
    accent: 'moss',
    startHref: '/chat/sensei?briefing=convenience-store&type=roleplay',
    summary: 'Handle checkout, bags, payment, and quick store questions.',
    headsUp: [
      'Most questions are yes/no at checkout.',
      '聞き取れない is okay — ask for repetition.',
      'Practice declining politely: 大丈夫です.',
    ],
    prep: ['袋はいりますか', 'カードでお願いします', '大丈夫です'],
  },
  'job-interview': {
    kind: 'roleplay',
    title: 'Job Interview',
    jpTitle: '面接の練習',
    level: 'N2',
    minutes: 15,
    accent: 'correction',
    startHref: '/chat/sensei?briefing=job-interview&type=roleplay',
    summary: 'Prepare concise, respectful interview answers with structured follow-ups.',
    headsUp: [
      'Answer in short blocks: point, example, result.',
      'Use polite endings consistently.',
      'If you need time, say 少し考えてもいいですか.',
    ],
    prep: ['自己紹介をお願いします', '志望理由は何ですか', '少し考えてもいいですか'],
  },
  'teacher-teaching': {
    kind: 'roleplay',
    title: 'Teacher Teaching',
    jpTitle: '先生に質問する',
    level: 'N5',
    minutes: 10,
    accent: 'mustard',
    startHref: '/chat/sensei?briefing=teacher-teaching&type=roleplay',
    image: '/assets/bg_school_room_back.jpg',
    summary: 'Ask a teacher for clarification and practice saying what you do not understand.',
    headsUp: [
      'Be direct but polite about confusion.',
      'Ask for examples when grammar feels abstract.',
      'KAIwa will break explanations into smaller steps.',
    ],
    prep: ['わかりません', '例をください', 'もう一度お願いします'],
  },
  'custom-roleplay': {
    kind: 'roleplay',
    title: 'Custom Roleplay',
    jpTitle: 'カスタム会話',
    level: 'Adaptive',
    minutes: 10,
    accent: 'mustard',
    startHref: '/chat/sensei?briefing=custom-roleplay&type=roleplay',
    summary: 'Describe any situation and KAIwa will create a guided conversation scene.',
    headsUp: [
      'Tell KAIwa your role, the other person, and the goal.',
      'You can ask to restart the scene if it drifts.',
      'No cloud calls by default; external providers are opt-in.',
    ],
    prep: ['場面は ___ です', '私は ___ です', '目標は ___ です'],
  },
};

export function getBriefing(id) {
  return BRIEFINGS[id] ?? null;
}

export function getBriefingIds() {
  return Object.keys(BRIEFINGS);
}
